/** Central route paths — extend as new screens ship (backend can align API routes separately). */
export const paths = {
  home: '/',
  /** Broker / logged-in app shell (protect with auth in production). */
  dashboard: '/dashboard',
  campaigns: '/campaigns',
  campaignsCreate: '/campaigns/create',
  brokerReferrals: '/referrals',
  brokerReferralCreate: '/referrals/create',
  brokerReferralDetail: (referralId: string) => `/referrals/${referralId}`,
  campaignDetail: (campaignId: string) => `/campaigns/${campaignId}`,
  campaignReferralDetail: (campaignId: string, referralId: string) =>
    `/campaigns/${campaignId}/referrals/${referralId}`,
  adminBase: '/admin',
  admin: {
    dashboard: '/admin',
    customers: '/admin/customers',
    customerDetail: (customerId: string) => `/admin/customers/${customerId}`,
    brokers: '/admin/brokers',
    referrals: '/admin/referrals',
    referralReview: (referralId: string) => `/admin/referrals/${referralId}`,
    rewards: '/admin/rewards',
    aiInsights: '/admin/ai-insights',
    reports: '/admin/reports',
    usersRoles: '/admin/users-roles',
    settings: '/admin/settings',
  },
  userBase: '/user',
  user: {
    dashboard: '/user',
    profile: '/user/profile',
    rewards: '/user/rewards',
    notifications: '/user/notifications',
  },
  /** Account settings (profile, password) — same shell as broker app. */
  settings: '/settings',
  settingsChangePassword: '/settings/change-password',
  login: '/login',
  signup: '/signup',
  auth: {
    forgotPassword: '/recover-password',
    checkEmail: '/check-email',
    resetPassword: '/reset-password',
    emailConfirmed: '/email-confirmed',
  },
  legal: {
    agreements: '/legal/agreements',
    privacy: '/legal/privacy',
    complaints: '/complaints',
    vulnerability: '/legal/customer-vulnerability',
    cookies: '/legal/cookies',
  },
  business: {
    offers: '/business/offers',
    invest: '/business/invest',
    raiseFunds: '/business/raise-funds',
    creditCard: '/business/credit-card',
    mabrookTokens: '/business/mabrook-tokens',
    mabrookShares: '/business/mabrook-shares',
    liquidity: '/business/liquidity',
    benefits: '/business/benefits',
  },
} as const
